# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cb9833f96409293c55b7ee101fb0466d214a251a8d9669838652effef10b3e5c244be5c7426295f498b00d177510fd71a8c2d3d569f36fce30e84b1789fcfbe

test:
  secret_key_base: eeeb151c418dbfa369b682ff12b94856e4ca4151898f055fea78186cd831b91892df3c593c503d508ba7e82d713466adb9728f6cc36c382c98d0dc368490058b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
